export type Coordinates = {
  latitude: number;
  longitude: number;
};

export type Place = {
  placeId: string;
  name: string;
  formattedAddress?: string;
  distance: number; // in km
  type?: PlaceType | null;
  types?: string[]; // Para autocomplete
  active_users?: number; // Optional: number of active users currently at the place
};

export type NearbyPlacesResponse = { places: Place[] };

// Google Places Nearby Search supported place types
// Source: https://developers.google.com/maps/documentation/places/web-service/supported_types
// Note: Nearby Search only accepts ONE type per request; combine via multiple requests if needed.

export enum PlaceType {
  accounting = "accounting",
  airport = "airport",
  amusement_park = "amusement_park",
  aquarium = "aquarium",
  art_gallery = "art_gallery",
  atm = "atm",
  bakery = "bakery",
  bank = "bank",
  bar = "bar",
  beauty_salon = "beauty_salon",
  bicycle_store = "bicycle_store",
  book_store = "book_store",
  bowling_alley = "bowling_alley",
  bus_station = "bus_station",
  cafe = "cafe",
  campground = "campground",
  car_dealer = "car_dealer",
  car_rental = "car_rental",
  car_repair = "car_repair",
  car_wash = "car_wash",
  casino = "casino",
  cemetery = "cemetery",
  church = "church",
  city_hall = "city_hall",
  clothing_store = "clothing_store",
  convenience_store = "convenience_store",
  courthouse = "courthouse",
  dentist = "dentist",
  department_store = "department_store",
  doctor = "doctor",
  drugstore = "drugstore",
  electrician = "electrician",
  electronics_store = "electronics_store",
  embassy = "embassy",
  fire_station = "fire_station",
  florist = "florist",
  funeral_home = "funeral_home",
  furniture_store = "furniture_store",
  gas_station = "gas_station",
  gym = "gym",
  hair_care = "hair_care",
  hardware_store = "hardware_store",
  hindu_temple = "hindu_temple",
  home_goods_store = "home_goods_store",
  hospital = "hospital",
  insurance_agency = "insurance_agency",
  jewelry_store = "jewelry_store",
  laundry = "laundry",
  lawyer = "lawyer",
  library = "library",
  light_rail_station = "light_rail_station",
  liquor_store = "liquor_store",
  local_government_office = "local_government_office",
  locksmith = "locksmith",
  lodging = "lodging",
  meal_delivery = "meal_delivery",
  meal_takeaway = "meal_takeaway",
  mosque = "mosque",
  movie_rental = "movie_rental",
  movie_theater = "movie_theater",
  moving_company = "moving_company",
  museum = "museum",
  night_club = "night_club",
  painter = "painter",
  park = "park",
  parking = "parking",
  pet_store = "pet_store",
  pharmacy = "pharmacy",
  physiotherapist = "physiotherapist",
  plumber = "plumber",
  police = "police",
  post_office = "post_office",
  primary_school = "primary_school",
  real_estate_agency = "real_estate_agency",
  restaurant = "restaurant",
  roofing_contractor = "roofing_contractor",
  rv_park = "rv_park",
  school = "school",
  secondary_school = "secondary_school",
  shoe_store = "shoe_store",
  shopping_mall = "shopping_mall",
  spa = "spa",
  stadium = "stadium",
  storage = "storage",
  store = "store",
  subway_station = "subway_station",
  supermarket = "supermarket",
  synagogue = "synagogue",
  taxi_stand = "taxi_stand",
  tourist_attraction = "tourist_attraction",
  train_station = "train_station",
  transit_station = "transit_station",
  travel_agency = "travel_agency",
  university = "university",
  veterinary_care = "veterinary_care",
  zoo = "zoo",
}

export const ALL_PLACE_TYPES: PlaceType[] = Object.values(PlaceType);

// Optional: human-friendly labels
export const PLACE_TYPE_LABEL: Record<PlaceType, string> = {
  [PlaceType.accounting]: "Accounting",
  [PlaceType.airport]: "Airport",
  [PlaceType.amusement_park]: "Amusement Park",
  [PlaceType.aquarium]: "Aquarium",
  [PlaceType.art_gallery]: "Art Gallery",
  [PlaceType.atm]: "ATM",
  [PlaceType.bakery]: "Bakery",
  [PlaceType.bank]: "Bank",
  [PlaceType.bar]: "Bar",
  [PlaceType.beauty_salon]: "Beauty Salon",
  [PlaceType.bicycle_store]: "Bicycle Store",
  [PlaceType.book_store]: "Book Store",
  [PlaceType.bowling_alley]: "Bowling Alley",
  [PlaceType.bus_station]: "Bus Station",
  [PlaceType.cafe]: "Cafe",
  [PlaceType.campground]: "Campground",
  [PlaceType.car_dealer]: "Car Dealer",
  [PlaceType.car_rental]: "Car Rental",
  [PlaceType.car_repair]: "Car Repair",
  [PlaceType.car_wash]: "Car Wash",
  [PlaceType.casino]: "Casino",
  [PlaceType.cemetery]: "Cemetery",
  [PlaceType.church]: "Church",
  [PlaceType.city_hall]: "City Hall",
  [PlaceType.clothing_store]: "Clothing Store",
  [PlaceType.convenience_store]: "Convenience Store",
  [PlaceType.courthouse]: "Courthouse",
  [PlaceType.dentist]: "Dentist",
  [PlaceType.department_store]: "Department Store",
  [PlaceType.doctor]: "Doctor",
  [PlaceType.drugstore]: "Drugstore",
  [PlaceType.electrician]: "Electrician",
  [PlaceType.electronics_store]: "Electronics Store",
  [PlaceType.embassy]: "Embassy",
  [PlaceType.fire_station]: "Fire Station",
  [PlaceType.florist]: "Florist",
  [PlaceType.funeral_home]: "Funeral Home",
  [PlaceType.furniture_store]: "Furniture Store",
  [PlaceType.gas_station]: "Gas Station",
  [PlaceType.gym]: "Gym",
  [PlaceType.hair_care]: "Hair Care",
  [PlaceType.hardware_store]: "Hardware Store",
  [PlaceType.hindu_temple]: "Hindu Temple",
  [PlaceType.home_goods_store]: "Home Goods Store",
  [PlaceType.hospital]: "Hospital",
  [PlaceType.insurance_agency]: "Insurance Agency",
  [PlaceType.jewelry_store]: "Jewelry Store",
  [PlaceType.laundry]: "Laundry",
  [PlaceType.lawyer]: "Lawyer",
  [PlaceType.library]: "Library",
  [PlaceType.light_rail_station]: "Light Rail Station",
  [PlaceType.liquor_store]: "Liquor Store",
  [PlaceType.local_government_office]: "Local Government Office",
  [PlaceType.locksmith]: "Locksmith",
  [PlaceType.lodging]: "Lodging",
  [PlaceType.meal_delivery]: "Meal Delivery",
  [PlaceType.meal_takeaway]: "Meal Takeaway",
  [PlaceType.mosque]: "Mosque",
  [PlaceType.movie_rental]: "Movie Rental",
  [PlaceType.movie_theater]: "Movie Theater",
  [PlaceType.moving_company]: "Moving Company",
  [PlaceType.museum]: "Museum",
  [PlaceType.night_club]: "Night Club",
  [PlaceType.painter]: "Painter",
  [PlaceType.park]: "Park",
  [PlaceType.parking]: "Parking",
  [PlaceType.pet_store]: "Pet Store",
  [PlaceType.pharmacy]: "Pharmacy",
  [PlaceType.physiotherapist]: "Physiotherapist",
  [PlaceType.plumber]: "Plumber",
  [PlaceType.police]: "Police",
  [PlaceType.post_office]: "Post Office",
  [PlaceType.primary_school]: "Primary School",
  [PlaceType.real_estate_agency]: "Real Estate Agency",
  [PlaceType.restaurant]: "Restaurant",
  [PlaceType.roofing_contractor]: "Roofing Contractor",
  [PlaceType.rv_park]: "RV Park",
  [PlaceType.school]: "School",
  [PlaceType.secondary_school]: "Secondary School",
  [PlaceType.shoe_store]: "Shoe Store",
  [PlaceType.shopping_mall]: "Shopping Mall",
  [PlaceType.spa]: "Spa",
  [PlaceType.stadium]: "Stadium",
  [PlaceType.storage]: "Storage",
  [PlaceType.store]: "Store",
  [PlaceType.subway_station]: "Subway Station",
  [PlaceType.supermarket]: "Supermarket",
  [PlaceType.synagogue]: "Synagogue",
  [PlaceType.taxi_stand]: "Taxi Stand",
  [PlaceType.tourist_attraction]: "Tourist Attraction",
  [PlaceType.train_station]: "Train Station",
  [PlaceType.transit_station]: "Transit Station",
  [PlaceType.travel_agency]: "Travel Agency",
  [PlaceType.university]: "University",
  [PlaceType.veterinary_care]: "Veterinary Care",
  [PlaceType.zoo]: "Zoo",
};
