/// <reference types="https://deno.land/x/supabase@1.7.4/functions/types.ts" />
import { createClient } from "https://esm.sh/@supabase/supabase-js@2.48.0";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers":
    "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, OPTIONS",
  "Content-Type": "application/json",
};

/**
 * skip-encounter Edge Function
 *
 * Permanently removes user_encounters rows for skipped users.
 * This is a "not now" action — encounters may reappear if
 * regenerated by the process-encounter worker.
 *
 * Accepts:
 *   { other_user_ids: string[] }
 */
Deno.serve(async (req) => {
  if (req.method === "OPTIONS") {
    return new Response("ok", { headers: corsHeaders });
  }

  if (req.method !== "POST") {
    return new Response(JSON.stringify({ error: "method_not_allowed" }), {
      status: 405,
      headers: corsHeaders,
    });
  }

  try {
    const authHeader = req.headers.get("Authorization") || "";
    const token = authHeader.replace("Bearer ", "").trim();

    if (!token) {
      return new Response(JSON.stringify({ error: "unauthorized" }), {
        status: 401,
        headers: corsHeaders,
      });
    }

    const supabaseUrl = Deno.env.get("SUPABASE_URL");
    const supabaseAnonKey = Deno.env.get("SUPABASE_ANON_KEY");
    const supabaseServiceKey = Deno.env.get("SUPABASE_SERVICE_ROLE_KEY");

    if (!supabaseUrl || !supabaseAnonKey) {
      return new Response(
        JSON.stringify({ error: "config_missing" }),
        { status: 500, headers: corsHeaders }
      );
    }

    const authClient = createClient(supabaseUrl, supabaseAnonKey, {
      global: { headers: { Authorization: `Bearer ${token}` } },
    });
    const serviceClient = supabaseServiceKey
      ? createClient(supabaseUrl, supabaseServiceKey)
      : null;
    const dbClient = serviceClient || authClient;

    const {
      data: { user },
      error: authError,
    } = await authClient.auth.getUser();

    if (authError || !user?.id) {
      return new Response(JSON.stringify({ error: "unauthorized" }), {
        status: 401,
        headers: corsHeaders,
      });
    }

    const body = await req.json().catch(() => null);
    const otherUserIds: string[] = body?.other_user_ids;

    if (
      !Array.isArray(otherUserIds) ||
      otherUserIds.length === 0 ||
      otherUserIds.some((id) => typeof id !== "string")
    ) {
      return new Response(
        JSON.stringify({ error: "invalid_other_user_ids" }),
        { status: 400, headers: corsHeaders }
      );
    }

    // Delete encounters where the authenticated user is involved
    // user_encounters has constraint user_a_id < user_b_id, so we check both positions
    const userId = user.id;
    let deletedCount = 0;

    for (const otherId of otherUserIds) {
      const { count, error: deleteError } = await dbClient
        .from("user_encounters")
        .delete({ count: "exact" })
        .or(
          `and(user_a_id.eq.${userId},user_b_id.eq.${otherId}),and(user_a_id.eq.${otherId},user_b_id.eq.${userId})`
        );

      if (deleteError) {
        console.error("skip-encounter delete error:", deleteError);
        continue;
      }

      deletedCount += count ?? 0;
    }

    return new Response(
      JSON.stringify({ status: "ok", deleted: deletedCount }),
      { headers: corsHeaders }
    );
  } catch (err: any) {
    console.error("skip-encounter unexpected error:", err);
    return new Response(
      JSON.stringify({
        error: "internal_error",
        message: err?.message ?? "Unexpected error",
      }),
      { status: 500, headers: corsHeaders }
    );
  }
});
